# Generated by Django 3.2.3 on 2021-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroNoticia', models.IntegerField()),
                ('tituloNoticia', models.CharField(max_length=75)),
                ('descripcioCorta', models.CharField(max_length=100)),
                ('descripcioLarga', models.CharField(max_length=1000)),
                ('fechaNoticia', models.DateField()),
            ],
        ),
    ]
